import {
  DataBoard,
  Grid,
  ChatSquare,
  DataLine,
  Setting,
  TrendCharts,
  CaretBottom,
  CaretRight,
  CaretTop,
  CaretLeft,
  Bell,
  User,
  UserFilled,
  Search,
  Plus,
  Edit,
  Delete,
  Download,
  Upload,
  Document,
  Cpu,
  Message,
  Clock,
  Lock,
  Reading,
  Filter,
  More,
  Refresh,
  Folder,
  Check,
  Close,
  Phone,
  Monitor,
  Management,
  Connection,
  Cloudy,
  Warning,
  CircleCheck,
  InfoFilled,
  Help,
  Picture,
  FolderOpened,
  FolderAdd,
  PriceTag,
  Calendar,
  Key,
  PieChart,
  Top,
  Bottom,
  Aim,
  Briefcase,
  Lightning,
  Comment,
  HomeFilled,
  Tools,
  Link,
  Memo,
  CopyDocument,
  RefreshLeft,
  RefreshRight,
  List,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Box,
  Coin,
  Histogram,
  View,
  Files,
  Money,
  Operation,
  WalletFilled
} from '@element-plus/icons-vue'

export const icons = {
  Database: DataBoard,
  LayoutDashboard: Grid,
  MessageSquare: ChatSquare,
  Robot: Cpu,
  FlowChart: DataLine,
  Settings: Setting,
  Activity: TrendCharts,
  ChevronDown: CaretBottom,
  ChevronRight: CaretRight,
  ChevronUp: CaretTop,
  ChevronLeft: CaretLeft,
  Bell,
  User,
  LogOut: ArrowRight,
  Search,
  Plus,
  Edit,
  Delete,
  Download,
  Upload,
  FileText: Document,
  Cpu,
  Send: Message,
  History: Clock,
  Clock,
  Eye: View,
  Lock,
  BookOpen: Reading,
  Shield: CircleCheck,
  Trash: Delete,
  Filter,
  More,
  Refresh,
  Folder,
  Check,
  X: Close,
  Mail: Message,
  Phone,
  HardDrive: Monitor,
  Server: Management,
  Network: Connection,
  Cloud: Cloudy,
  AlertCircle: Warning,
  CheckCircle: CircleCheck,
  Info: InfoFilled,
  HelpCircle: Help,
  Wifi: Connection,
  WifiOff: Connection,
  File: Document,
  FileImage: Picture,
  FileExcel: Document,
  FileWord: Document,
  FilePdf: Document,
  FolderOpen: FolderOpened,
  FolderPlus: FolderAdd,
  Tag: PriceTag,
  Tags: PriceTag,
  Calendar,
  CalendarDays: Calendar,
  UserPlus: UserFilled,
  UserMinus: User,
  UserCheck: Check,
  UserX: Close,
  Key,
  ShieldPlus: CircleCheck,
  ShieldCheck: CircleCheck,
  ShieldAlert: Warning,
  Settings2: Setting,
  BarChart3: Histogram,
  PieChart,
  LineChart: TrendCharts,
  TrendingUp: Top,
  TrendingDown: Bottom,
  Target: Aim,
  Rocket: Briefcase,
  Zap: Lightning,
  Lightbulb: Comment,
  MessageCircle: Comment,
  Home: HomeFilled,
  Apartment: HomeFilled,
  Wrench: Tools,
  Screwdriver: Tools,
  Hammer: Tools,
  Paperclip: Link,
  ClipboardList: Memo,
  ClipboardCheck: Check,
  FileEdit: Edit,
  FileSearch: Search,
  Copy: CopyDocument,
  Paste: CopyDocument,
  Cut: Delete,
  Undo: RefreshLeft,
  Redo: RefreshRight,
  Bold: Edit,
  Italic: Edit,
  Underline: Edit,
  AlignLeft: List,
  AlignCenter: List,
  AlignRight: List,
  AlignJustify: List,
  List,
  ListOrdered: List,
  ListUnordered: List,
  Quote: Message,
  Code: Document,
  Terminal: Monitor,
  GitBranch: Document,
  GitCommit: Document,
  GitMerge: Document,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Square: Box,
  Circle: Coin,
  Triangle: Box,
  Hexagon: Box,
  Maximize: View,
  Minimize: View,
  Fullscreen: View,
  Layers: Files,
  Grid3X3: Grid,
  Grid2X2: Grid,
  DollarSign: Money,
  Percent: Operation,
  CreditCard: WalletFilled,
  Wallet: WalletFilled,
  Banknote: Coin,
  Coins: Coin,
  ShoppingBag: Box,
  ShoppingCart: Box,
  Package: Box,
  Box,
  Truck: Briefcase
}
